/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const DemosConfig = IDL.Record({
    wasm_registry_id: IDL.Principal,
    trial_duration_ns: IDL.Nat64,
    installer_origin: IDL.Text,
    cycles_per_demo_canister: IDL.Nat,
    pool_target_size: IDL.Nat32,
  });
  const GenericResult = IDL.Variant({ Ok: IDL.Null, Err: IDL.Text });
  const GenerateCodesResult = IDL.Variant({
    Ok: IDL.Vec(IDL.Text),
    Err: IDL.Text,
  });
  const ActiveDemo = IDL.Record({
    dapp_principal: IDL.Principal,
    canister_id: IDL.Principal,
    service_principal: IDL.Principal,
    expires_at: IDL.Nat64,
    started_at: IDL.Nat64,
    access_code: IDL.Text,
    wasm_name: IDL.Text,
  });
  const PoolStatus = IDL.Record({
    active: IDL.Nat32,
    available: IDL.Nat32,
  });
  const AccessCodeStatus = IDL.Variant({
    Available: IDL.Null,
    Redeemed: IDL.Record({
      dapp_principal: IDL.Opt(IDL.Principal),
      canister_id: IDL.Principal,
      service_principal: IDL.Principal,
      wasm_name: IDL.Text,
    }),
    Expired: IDL.Null,
  });
  const AccessCode = IDL.Record({
    status: AccessCodeStatus,
    code: IDL.Text,
    created_at: IDL.Nat64,
    redeemed_at: IDL.Opt(IDL.Nat64),
  });
  const RedeemResult = IDL.Variant({
    Ok: IDL.Record({ canister_id: IDL.Principal }),
    Err: IDL.Text,
  });

  return IDL.Service({
    configure: IDL.Func([DemosConfig], [GenericResult], []),
    finalize_demo: IDL.Func([IDL.Text, IDL.Principal], [GenericResult], []),
    generate_access_codes: IDL.Func([IDL.Nat32], [GenerateCodesResult], []),
    get_config: IDL.Func([], [IDL.Opt(DemosConfig)], ['query']),
    get_my_demos: IDL.Func([], [IDL.Vec(ActiveDemo)], ['query']),
    get_pool_status: IDL.Func([], [PoolStatus], ['query']),
    is_admin: IDL.Func([], [IDL.Bool], ['query']),
    list_access_codes: IDL.Func([], [IDL.Vec(AccessCode)], ['query']),
    list_active_demos: IDL.Func([], [IDL.Vec(ActiveDemo)], ['query']),
    reclaim_expired: IDL.Func([], [GenericResult], []),
    redeem_code: IDL.Func([IDL.Text, IDL.Text], [RedeemResult], []),
    replenish_pool: IDL.Func([], [GenericResult], []),
    set_admins: IDL.Func([IDL.Vec(IDL.Principal)], [GenericResult], []),
    validate_code: IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => {
  return [];
};
