name: Publish Vite Plugin Package

on:
  push:
    tags:
      - 'web3nl/vite-plugin-canister-dapp-v*'

jobs:
  publish:
    name: Publish to NPM and GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build --workspace=@web3nl/vite-plugin-canister-dapp

      - name: Build documentation
        run: npm run build:docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create docs structure
        run: |
          mkdir -p ./pages-deploy/web3nl-vite-plugin-canister-dapp
          cp -r ./my-canister-dapp-js/vite-plugin-canister-dapp/docs/* ./pages-deploy/web3nl-vite-plugin-canister-dapp/

      - name: Upload docs to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './pages-deploy'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
