name: Shared Build and Test

on:
  workflow_call:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      # Prefer IPv4 DNS results in Node (affects dev servers, tooling, etc.)
      NODE_OPTIONS: --dns-result-order=ipv4first

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: 0.28.0

      - name: Prefer IPv4 for localhost on runner
        run: |
          set -euxo pipefail
          echo '127.0.0.1 localhost' | sudo tee -a /etc/hosts
          echo 'precedence ::ffff:0:0/96  100' | sudo tee -a /etc/gai.conf
          getent hosts localhost || true

      - name: Build, validate and run tests (E2E)
        run: ./validate-and-test-all.sh --e2e
