/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessCode {
  status: AccessCodeStatus;
  code: string;
  created_at: bigint;
  redeemed_at: [] | [bigint];
}
export type AccessCodeStatus =
  | { Available: null }
  | {
      Redeemed: {
        dapp_principal: [] | [Principal];
        canister_id: Principal;
        service_principal: Principal;
        wasm_name: string;
      };
    }
  | { Expired: null };
export interface ActiveDemo {
  dapp_principal: Principal;
  canister_id: Principal;
  service_principal: Principal;
  expires_at: bigint;
  started_at: bigint;
  access_code: string;
  wasm_name: string;
}
export interface DemosConfig {
  wasm_registry_id: Principal;
  trial_duration_ns: bigint;
  installer_origin: string;
  cycles_per_demo_canister: bigint;
  pool_target_size: number;
}
export type GenerateCodesResult = { Ok: Array<string> } | { Err: string };
export type GenericResult = { Ok: null } | { Err: string };
export interface PoolStatus {
  active: number;
  available: number;
}
export type RedeemResult = { Ok: { canister_id: Principal } } | { Err: string };
export interface SelfStatus {
  cycles_balance: bigint;
  pool_available: number;
  pool_target: number;
  total_codes: number;
  active_demos: number;
}
export interface _SERVICE {
  configure: ActorMethod<[DemosConfig], GenericResult>;
  finalize_demo: ActorMethod<[string, Principal], GenericResult>;
  generate_access_codes: ActorMethod<[number], GenerateCodesResult>;
  get_config: ActorMethod<[], [] | [DemosConfig]>;
  get_my_demos: ActorMethod<[], Array<ActiveDemo>>;
  get_pool_status: ActorMethod<[], PoolStatus>;
  get_self_status: ActorMethod<[], SelfStatus>;
  is_admin: ActorMethod<[], boolean>;
  list_access_codes: ActorMethod<[], Array<AccessCode>>;
  list_active_demos: ActorMethod<[], Array<ActiveDemo>>;
  reclaim_expired: ActorMethod<[], GenericResult>;
  redeem_code: ActorMethod<[string, string], RedeemResult>;
  replenish_pool: ActorMethod<[], GenericResult>;
  set_admins: ActorMethod<[Array<Principal>], GenericResult>;
  validate_code: ActorMethod<[string], boolean>;
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
